FROM golang:alpine

RUN apk add build-base
RUN GO111MODULE=on go install github.com/jaeles-project/jaeles@latest

WORKDIR /root/

COPY ./test-signatures/ ./custom-signatures/

RUN jaeles config init
RUN jaeles config reload --signDir ~/custom-signatures/
CMD jaeles server --host 0.0.0.0 -A -L 4 --verbose