export const distinctHashAgg = {
  $group: {
    _id: '$hash',
    requestPacketId: { $first: '$requestPacketId' },
    requestPacketIndex: { $first: '$requestPacketIndex' },
    requestPacketPrefix: { $first: '$requestPacketPrefix' },
    requestHttpVersion: { $first: '$requestHttpVersion' },
    toolName: { $first: '$toolName' },
    method: { $first: '$method' },
    requestLength: { $first: '$requestLength' },
    requestContentType: { $first: '$requestContentType' },
    referer: { $first: '$referer' },
    protocol: { $first: '$protocol' },
    origin: { $first: '$origin' },
    port: { $first: '$port' },
    path: { $first: '$path' },
    hasBodyParam: { $first: '$hasBodyParam' },
    querystring: { $first: '$querystring' },
    requestBodyHash: { $first: '$requestBodyHash' },
    responseBodyHash: { $first: '$responseBodyHash' },
    parameters: { $first: '$parameters' },
    requestHeaders: { $first: '$requestHeaders' },
    requestCookies: { $first: '$requestCookies' },
    responseStatus: { $first: '$responseStatus' },
    responseContentType: { $first: '$responseContentType' },
    responseStatusText: { $first: '$responseStatusText' },
    responseLength: { $first: '$responseLength' },
    responseMimeType: { $first: '$responseMimeType' },
    responseHttpVersion: { $first: '$responseHttpVersion' },
    responseInferredMimeType: { $first: '$responseInferredMimeType' },
    responseCookies: { $first: '$responseCookies' },
    responseHeaders: { $first: '$responseHeaders' },
    rtt: { $first: '$rtt' },
    staticScore: { $first: '$staticScore' },
    project: { $first: '$project' },
    codeName: { $first: '$codeName' },
    hash: { $first: '$hash' },
    count: { $first: '$count' },
    createdAt: { $first: '$createdAt' },
    updatedAt: { $first: '$updatedAt' },
  },
};

export const projectAgg = {
  $project: {
    requestPacketId: 1,
    requestPacketIndex: 1,
    requestPacketPrefix: 1,
    requestHttpVersion: 1,
    toolName: 1,
    method: 1,
    requestLength: 1,
    requestContentType: 1,
    referer: 1,
    protocol: 1,
    origin: 1,
    port: 1,
    path: 1,
    hasBodyParam: 1,
    querystring: 1,
    requestBodyHash: 1,
    responseBodyHash: 1,
    parameters: 1,
    requestHeaders: 1,
    requestCookies: 1,
    responseStatus: 1,
    responseContentType: 1,
    responseStatusText: 1,
    responseLength: 1,
    responseMimeType: 1,
    responseHttpVersion: 1,
    responseInferredMimeType: 1,
    responseCookies: 1,
    responseHeaders: 1,
    rtt: 1,
    staticScore: 1,
    project: 1,
    codeName: 1,
    hash: '$count.hash',
    count: '$count.count',
    createdAt: 1,
    updatedAt: 1,
  },
};
