FROM node:16-buster as builder

WORKDIR /app

COPY . .
RUN npm i && npm run build

FROM nginx:latest

COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
